# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1usTLuXOIDY8RykhWBUG5TZ2fB2iIcRI2
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pipeline import run_pipeline

st.title(" Credit Card Fraud  ML Project")

file = st.file_uploader("Upload CSV File")

if file is not None:

   st.write("File Uploaded")
   if not file.name.endswith(".csv"):
    st.error("Please upload a CSV file")
    st.stop()

   st.write("CSV Check Passed")
   try:
      df = pd.read_csv(file)
   except:
    st.error("Invalid CSV file")
    st.stop()


   st.write("Dataset Preview")
   st.dataframe(df.head())

   target_col = st.selectbox("Select Target Column", df.columns)

   if st.button("Run Pipeline"):
        st.write("Data Loaded")

        if not pd.api.types.is_numeric_dtype(df[target_col]):
          st.warning("Target column must contain numeric values(0 an 1 only) please convert categorical values before uploading.")
          st.stop()


        if df[target_col].nunique() != 2:
          st.error("Target column must have 2 unique values.")
          st.stop()

        st.write("Target Check Passed")


        st.write("All Checks Passed")
        result = run_pipeline(df, target_col)

        st.success("Pipeline executed successfully")
        st.write("Target Column:", result["target"])

        st.subheader("Data Shape")
        st.write(result["shape"])

        st.subheader("Missing Values")
        st.dataframe(result["missing"])

        st.subheader("Outliers")
        for col, count in result["outliers"].items():
            st.write(f"{col} has {int(count)} outliers")

        st.subheader("Model Results")

        for name, metrics in result["results"].items():
          st.subheader(name.replace('_',' ').title())

          st.write("Accuracy", metrics["accuracy"])

          st.write("Classification Report")
          report_df = pd.DataFrame(metrics["report"]).transpose()
          st.dataframe(report_df)

          st.write("Confusion Matrix")
          fig, ax = plt.subplots()
          sns.heatmap(metrics["cm"], annot=True, fmt='d', cmap = "Blues", ax=ax)
          st.pyplot(fig)

          st.markdown("---")

        st.subheader("Best Model")
        st.write(result["best_model_name"].replace("_"," ").title())

        st.subheader("Target Distribution")

        counts = result["target_counts"]

        for key,value in counts.items():
          st.write(f"{key}: {value}")