# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1usTLuXOIDY8RykhWBUG5TZ2fB2iIcRI2
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pipeline import run_pipeline

st.title("ML Classification Web App")

st.warning("""
Upload a valid CSV file for fraud and casual prediction.

Make sure your dataset has a target column with only 0 and 1 values 
. The data should be clean, properly formatted, 
and should not contain incorrect or mixed values.

Incorrect data format may cause errors or wrong predictions.
""")

file = st.file_uploader("Upload CSV File")

if file is not None:

   st.write("File Uploaded")
   if not file.name.endswith(".csv"):
    st.error("Please upload a CSV file")
    st.stop()

   st.write("CSV Check Passed")
   try:
      df = pd.read_csv(file)
   except:
    st.error("Invalid CSV file")
    st.stop()


   st.write("Dataset Preview")
   st.dataframe(df.head())

   target_col = st.selectbox("Select Target Column", df.columns)

   if st.button("Run Pipeline"):
        st.write("Data Loaded")

        if not pd.api.types.is_numeric_dtype(df[target_col]):
          st.warning("Target column must contain numeric values(0 an 1 only) please convert categorical values before uploading.")
          st.stop()


        if df[target_col].nunique() != 2:
          st.error("Target column must have 2 unique values.")
          st.stop()

        st.write("Target Check Passed")


        st.write("All Checks Passed")
        result = run_pipeline(df, target_col)

        st.success("Pipeline executed successfully")
        st.write("Target Column:", result["target"])

        st.subheader("Data Shape")
        st.write(result["shape"])

        st.subheader("Missing Values")
        st.dataframe(result["missing"])

        st.subheader("Outliers")
        for col, count in result["outliers"].items():
            st.write(f"{col} has {int(count)} outliers")

        st.subheader("Best Model")

        best_name = result["best_model_name"]
        best = result["results"][best_name]

        st.write(best_name.replace('_',' ').title())

        st.write("Accuracy", best["accuracy"])

        st.write("Classification Report")
        report_df = pd.DataFrame(best["report"]).transpose()
        st.dataframe(report_df)

        st.write("Confusion Matrix")
        fig, ax = plt.subplots()
        sns.heatmap(best["cm"], annot=True, fmt='d', cmap = "Blues", ax=ax)
        st.pyplot(fig)

        st.subheader("Target Distribution")

        counts = result["target_counts"]

        for key,value in counts.items():
          st.write(f"{key}: {value}")
    st.subheader("Predict Fraud for New Transaction")

    input_data = {}

    for col in df.columns:
       if col == result["target"]:
          continue
       input_data[col] = st.text_input(f"Enter {col}")

    if st.button("Predict Fraud", key="fraud_btn"):

       input_df = pd.DataFrame([input_data])

       for col in input_df.columns:
           try:
              input_df[col] = pd.to_numeric(input_df[col])
           except:
              pass

       model = result["best_model"]
       pred = model.predict(input_df)[0]

       if pred == 1:
          st.error("🚨 Fraud Detected")
       else:
          st.success("✅ Non-Fraud Transaction")
