# -*- coding: utf-8 -*-
"""pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MQfpw3jPnFcvmvMcW_IBOo3lv9b9BLlM
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import streamlit as st
import joblib

def load_data(file):   # Load CSV file into pandas dataframe.

  try:
      df = pd.read_csv(file)

      print("Data loaded successfully")
      print(f"Data head: {df.head()}")
      print(f"Shape of data: {df.shape}")
      df.info()
      print(f"data describe: {df.describe()}")

      return df
  except Exception as e:
      print("Error loading file:", e)
      return None

def handle_missing_values(df):
    ''' Handle missing values in dataset using pandas dataframe
       and returns a cleaned dataframe (df)'''
    missing_report = df.isna().sum()

    print(" Missing Values Before Handling:")
    print(missing_report)

    for col in df.columns:

        if df[col].isnull().sum() == 0:
            continue

        # Numeric columns
        if df[col].dtype.kind in 'biufc':   # it is better than int64/float64
            df[col] = df[col].fillna(df[col].median())

        # Categorical columns
        else:
            df[col] = df[col].fillna(df[col].mode()[0])

    print("\n Missing Values Handled Successfully.")

    return df, missing_report

def detect_target_col(df):

    print("Columns:", df.columns)

    target_col = input("Enter Target Column Name: ")   # manually taking target column
    return target_col

def detect_outliers(df, target_col):  # detecting outliers using IQR Method

    outlier_report = {}

    for col in df.columns:
        if col == target_col:
           continue

        if df[col].dtype.kind not in 'biufc':
           continue

        q1 = df[col].quantile(0.25)
        q3 = df[col].quantile(0.75)
        iqr = q3 - q1

        lower = q1 - 1.5 * iqr
        upper = q3 + 1.5 * iqr

        count = ((df[col] < lower) | (df[col] > upper)).sum()

        outlier_report[col] = count

    print("\n outlier_report: ")
    for col, count in outlier_report.items():
        print(f"{col} has: {count} outliers")

    return outlier_report

def handle_outliers(df, target_col):
  '''  handling outliers using clipping instead of remove
   or delete them because it may cause data loss so clipped them'''

  for col in df.columns:

        if col == target_col:
           continue

        if df[col].dtype.kind not in 'biufc':
           continue

        q1 = df[col].quantile(0.25)
        q3 = df[col].quantile(0.75)
        iqr = q3 - q1

        lower = q1 - 1.5 * iqr
        upper = q3 + 1.5 * iqr

        df[col] = df[col].clip(lower, upper)

  print("\n Outiers Clipped Sucessfully")

  return df

def split_data(df, target_col):

    from sklearn.model_selection import train_test_split

    X = df.drop(columns=[target_col])
    y = df[target_col]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

    return X_train, X_test, y_train, y_test

def ml_models(use_smote):

    from sklearn.preprocessing import StandardScaler
    from sklearn.linear_model import LogisticRegression
    from sklearn.tree import DecisionTreeClassifier
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.svm import SVC
    from sklearn.neighbors import KNeighborsClassifier
    from imblearn.over_sampling import SMOTE
    from collections import Counter
    from imblearn.pipeline import Pipeline

    if use_smote:
        models = {
            'logistic': Pipeline([
                ('scaler', StandardScaler()),
                ('smote', SMOTE(k_neighbors=5, random_state=42)),
                ('logistic', LogisticRegression(max_iter=500, solver='liblinear'))
            ]),

            'decision_tree': Pipeline([
                ('smote', SMOTE(k_neighbors=5, random_state=42)),
                ('decision', DecisionTreeClassifier(max_depth=10, min_samples_split=10, random_state=42))
            ]),

            'random_forest': Pipeline([
                ('smote', SMOTE(k_neighbors=5, random_state=42)),
                ('rf', RandomForestClassifier(n_estimators=50, max_depth=10, n_jobs=-1, random_state=42))
            ]),

            'knn': Pipeline([
                ('scaler', StandardScaler()),
                ('smote', SMOTE(k_neighbors=5, random_state=42)),
                ('knn', KNeighborsClassifier(n_neighbors=5, algorithm='kd_tree'))
            ]),

            'svc': Pipeline([
                ('scaler', StandardScaler()),
                ('smote', SMOTE(k_neighbors=5, random_state=42)),
                ('svc', SVC(kernel='linear', max_iter=1000, tol=1e-2, class_weight='balanced'))
            ])
        }

    else:
        models = {
            'logistic': Pipeline([
                ('scaler', StandardScaler()),
                ('logistic', LogisticRegression(max_iter=500, solver='liblinear'))
            ]),

            'decision_tree': Pipeline([
                ('decision', DecisionTreeClassifier(max_depth=10, min_samples_split=10, random_state=42))
            ]),

            'random_forest': Pipeline([
                ('rf', RandomForestClassifier(n_estimators=50, max_depth=10, n_jobs=-1, random_state=42))
            ]),

            'knn': Pipeline([
                ('scaler', StandardScaler()),
                ('knn', KNeighborsClassifier(n_neighbors=5, algorithm='kd_tree'))
            ]),

            'svc': Pipeline([
                ('scaler', StandardScaler()),
                ('svc', SVC(kernel='linear', max_iter=1000, tol=1e-2, class_weight='balanced'))
            ])
        }

    return models

from sklearn.preprocessing import LabelEncoder

def encode_categorical(df, target_col):

    cat_cols = df.select_dtypes(include=['object']).columns

    for col in cat_cols:

        if col == target_col:
            continue

        if df[col].nunique() == 2:
            df[col] = LabelEncoder().fit_transform(df[col])
        else:
            df = pd.get_dummies(df, columns=[col], drop_first=True)

    return df

def target_count(df, target_col):
   return df[target_col].value_counts().to_dict()

def train_and_evaluate(models, X_train, X_test, y_train, y_test):

    from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

    results = {}

    for name, model in models.items():

        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

        acc = accuracy_score(y_test, y_pred)
        cm = confusion_matrix(y_test, y_pred)
        report = classification_report(y_test, y_pred, output_dict=True)

        results[name] = {
            "accuracy": acc,
            "cm": cm,
            "report": report,
            "model": model
        }

    return results

def plot_confusion_matrix(model, X_test, y_test):

    from sklearn.metrics import confusion_matrix

    y_pred = model.predict(X_test)
    cm = confusion_matrix(y_test, y_pred)

    labels = ["Non-Fraud", "Fraud"]

    plt.figure(figsize=(5,4))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=labels, yticklabels=labels)

    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.title("Confusion Matrix")
    plt.show()

def run_pipeline(df, target_col):

    df, _ = handle_missing_values(df)

    outliers = detect_outliers(df, target_col)

    df = handle_outliers(df, target_col)

    df = encode_categorical(df, target_col)

    X_train, X_test, y_train, y_test = split_data(df, target_col)
    from collections import Counter
    class_counts = Counter(y_train)
    minority = min(class_counts.values())
    majority = max(class_counts.values())
    imbalance_ratio = minority / majority
    use_smote = imbalance_ratio > 0.5

    models = ml_models(use_smote)

    results = train_and_evaluate(models, X_train, X_test, y_train, y_test)

    target_counts = df[target_col].value_counts().to_dict()

    best_model_name = max(results, key=lambda x: results[x]["accuracy"])
    best_model = results[best_model_name]["model"]

    print(f"\nBest Model: {best_model_name}")

    plot_confusion_matrix(best_model, X_test, y_test)

    return {
        "best_model_name": best_model_name,
        "best_model": best_model,
        "target": target_col,
        "shape": df.shape,
        "missing": df.isna().sum(),
        "outliers": outliers,
        "results": results,
        "target_counts": target_counts,
    }
